export type RootStackParamList = {
	Home: undefined;
	SplashScreen: undefined;
	KycStepsScreen: undefined;
	DashboardScreen: undefined;
	VerifyBvnScreen: undefined;
	OnboardingScreen: undefined;
	CreateUserScreen: undefined;
	VerifyEmailScreen: undefined;
	VerifyPhoneScreen: undefined;
	TransactionScreen: undefined;
	LoginScreen: { email?: string };
	ForgotPasswordScreen: undefined;
	BVNVerificationScreen: undefined;
	VerifyPhoneNumberScreen: undefined;
	EmailVerificationScreen: undefined;
	PhoneVerificationScreen: undefined;
	SetTransactionPinScreen: undefined;
	ResetPasswordScreen: { email: string };
	TailorYourExperienceScreen: undefined;
};
