export type RootStackParamList = {
	Home: undefined;
	SplashScreen: undefined;
	SendCADScreen: undefined;
	SendNGNScreen: undefined;
	KycStepsScreen: undefined;
	DashboardScreen: undefined;
	VerifyBvnScreen: undefined;
	OnboardingScreen: undefined;
	CreateUserScreen: undefined;
	VerifyEmailScreen: undefined;
	VerifyPhoneScreen: undefined;
	TransactionScreen: undefined;
	SendFundsBeneficiaryScreen: {
		currency: 'CAD' | 'NGN';
	};
	LoginScreen: { email?: string };
	ForgotPasswordScreen: undefined;
	BVNVerificationScreen: undefined;
	VerifyPhoneNumberScreen: undefined;
	EmailVerificationScreen: undefined;
	PhoneVerificationScreen: undefined;
	SetTransactionPinScreen: undefined;
	SendFundsFeedbackScreen: undefined;
	ResetPasswordScreen: { email: string };
	TailorYourExperienceScreen: undefined;
	AmountScreen: {
		lastName?: string;
		firstName?: string;
		accountName?: string;
		interacEmail?: string;
		accountNumber?: string;
		securityAnswer?: string;
		currency?: 'CAD' | 'NGN';
		securityQuestion?: string;
		saveAsBeneficiary?: boolean;
		narration?: string | undefined;
		bank?: { code: string; name: string };
		transactionType: 'SWAP' | 'CAD-to-CAD' | 'NGN-to-NGN';
	};
};
